# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastro_Clientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastrar_clientes(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(571, 430)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 571, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 571, 430))
        self.label_2.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.Nome_Cliente = QtWidgets.QLineEdit(Dialog)
        self.Nome_Cliente.setGeometry(QtCore.QRect(148, 105, 341, 20))
        self.Nome_Cliente.setObjectName("Nome_Cliente")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(150, 90, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.CPF_Cliente = QtWidgets.QLineEdit(Dialog)
        self.CPF_Cliente.setGeometry(QtCore.QRect(68, 150, 201, 20))
        self.CPF_Cliente.setObjectName("CPF_Cliente")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(68, 134, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Apelido_Ciente = QtWidgets.QLineEdit(Dialog)
        self.Apelido_Ciente.setGeometry(QtCore.QRect(276, 150, 211, 20))
        self.Apelido_Ciente.setObjectName("Apelido_Ciente")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(276, 134, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 8, 430))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(565, 0, 8, 430))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(0, 424, 571, 8))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.Endereo_Cliente = QtWidgets.QLineEdit(Dialog)
        self.Endereo_Cliente.setGeometry(QtCore.QRect(68, 195, 291, 20))
        self.Endereo_Cliente.setObjectName("Endereo_Cliente")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(68, 178, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.Nascimento = QtWidgets.QDateEdit(Dialog)
        self.Nascimento.setGeometry(QtCore.QRect(366, 195, 122, 20))
        self.Nascimento.setObjectName("Nascimento")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(366, 178, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Telefone_Cliente = QtWidgets.QLineEdit(Dialog)
        self.Telefone_Cliente.setGeometry(QtCore.QRect(68, 240, 151, 20))
        self.Telefone_Cliente.setObjectName("Telefone_Cliente")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(68, 222, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.Email_Cliente = QtWidgets.QLineEdit(Dialog)
        self.Email_Cliente.setGeometry(QtCore.QRect(226, 240, 261, 20))
        self.Email_Cliente.setObjectName("Email_Cliente")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(226, 222, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(329, 280, 121, 116))
        self.label_17.setStyleSheet("border-image: url(:/Cliente/Img/cadastro.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.btn_Cadastro_Cliente = QtWidgets.QPushButton(Dialog)
        self.btn_Cadastro_Cliente.setGeometry(QtCore.QRect(130, 280, 100, 23))
        self.btn_Cadastro_Cliente.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Cadastro_Cliente.setObjectName("btn_Cadastro_Cliente")
        self.btn_Cancelar_Cliente = QtWidgets.QPushButton(Dialog)
        self.btn_Cancelar_Cliente.setGeometry(QtCore.QRect(130, 327, 100, 23))
        self.btn_Cancelar_Cliente.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Cancelar_Cliente.setObjectName("btn_Cancelar_Cliente")
        self.btn_Cadastrar_Cliente = QtWidgets.QPushButton(Dialog)
        self.btn_Cadastrar_Cliente.setGeometry(QtCore.QRect(130, 372, 100, 23))
        self.btn_Cadastrar_Cliente.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Cadastrar_Cliente.setObjectName("btn_Cadastrar_Cliente")
        self.Nome_Cliente_2 = QtWidgets.QLineEdit(Dialog)
        self.Nome_Cliente_2.setGeometry(QtCore.QRect(68, 105, 73, 20))
        self.Nome_Cliente_2.setObjectName("Nome_Cliente_2")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(68, 90, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_2.raise_()
        self.label.raise_()
        self.Nome_Cliente.raise_()
        self.label_4.raise_()
        self.CPF_Cliente.raise_()
        self.label_5.raise_()
        self.Apelido_Ciente.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.Endereo_Cliente.raise_()
        self.label_10.raise_()
        self.Nascimento.raise_()
        self.label_11.raise_()
        self.Telefone_Cliente.raise_()
        self.label_12.raise_()
        self.Email_Cliente.raise_()
        self.label_13.raise_()
        self.label_17.raise_()
        self.btn_Cadastro_Cliente.raise_()
        self.btn_Cancelar_Cliente.raise_()
        self.btn_Cadastrar_Cliente.raise_()
        self.Nome_Cliente_2.raise_()
        self.label_14.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Cadastrar Clientes no Sistema</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Nome"))
        self.label_5.setText(_translate("Dialog", "CPF / CNPJ"))
        self.label_6.setText(_translate("Dialog", "Apelido"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "Endereço"))
        self.label_11.setText(_translate("Dialog", "Nascimento"))
        self.label_12.setText(_translate("Dialog", "Nº Telefone"))
        self.label_13.setText(_translate("Dialog", "E-mail"))
        self.btn_Cadastro_Cliente.setText(_translate("Dialog", "Cadastrar"))
        self.btn_Cancelar_Cliente.setText(_translate("Dialog", "Cancelar"))
        self.btn_Cadastrar_Cliente.setText(_translate("Dialog", "Limpar"))
        self.label_14.setText(_translate("Dialog", "ID"))
import icone_cliente


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_cadastrar_clientes()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
