# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastrar_Servicos.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastrar_servicos(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(572, 425)
        self.Fundo = QtWidgets.QLabel(Dialog)
        self.Fundo.setGeometry(QtCore.QRect(0, -4, 571, 430))
        self.Fundo.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.Fundo.setText("")
        self.Fundo.setObjectName("Fundo")
        self.Nome_Servico = QtWidgets.QLineEdit(Dialog)
        self.Nome_Servico.setGeometry(QtCore.QRect(190, 111, 230, 20))
        self.Nome_Servico.setObjectName("Nome_Servico")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(110, 96, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(290, 200, 121, 121))
        self.label.setStyleSheet("border-image: url(:/Servico/Img/Cadastro_Servico.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Preco_Servico = QtWidgets.QLineEdit(Dialog)
        self.Preco_Servico.setGeometry(QtCore.QRect(110, 156, 111, 20))
        self.Preco_Servico.setObjectName("Preco_Servico")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(230, 140, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, -4, 8, 430))
        self.label_3.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, -4, 571, 30))
        self.label_2.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(565, -4, 8, 430))
        self.label_9.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.ID_Servico = QtWidgets.QLineEdit(Dialog)
        self.ID_Servico.setGeometry(QtCore.QRect(110, 111, 73, 20))
        self.ID_Servico.setObjectName("ID_Servico")
        self.btn_Cadastro_Servico = QtWidgets.QPushButton(Dialog)
        self.btn_Cadastro_Servico.setGeometry(QtCore.QRect(130, 208, 100, 23))
        self.btn_Cadastro_Servico.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Cadastro_Servico.setObjectName("btn_Cadastro_Servico")
        self.OBS_Servico = QtWidgets.QLineEdit(Dialog)
        self.OBS_Servico.setGeometry(QtCore.QRect(228, 156, 191, 20))
        self.OBS_Servico.setObjectName("OBS_Servico")
        self.btn_Cancelar_Servico = QtWidgets.QPushButton(Dialog)
        self.btn_Cancelar_Servico.setGeometry(QtCore.QRect(130, 255, 100, 23))
        self.btn_Cancelar_Servico.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Cancelar_Servico.setObjectName("btn_Cancelar_Servico")
        self.btn_Limpar_Usuario = QtWidgets.QPushButton(Dialog)
        self.btn_Limpar_Usuario.setGeometry(QtCore.QRect(130, 300, 100, 23))
        self.btn_Limpar_Usuario.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Limpar_Usuario.setObjectName("btn_Limpar_Usuario")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, -4, 8, 430))
        self.label_4.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(192, 96, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 420, 571, 8))
        self.label_5.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(110, 140, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_7.setText(_translate("Dialog", "ID"))
        self.label_8.setText(_translate("Dialog", "Observação"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Cadastrar Serviços no Sistema</p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btn_Cadastro_Servico.setText(_translate("Dialog", "Cadastrar"))
        self.btn_Cancelar_Servico.setText(_translate("Dialog", "Cancelar"))
        self.btn_Limpar_Usuario.setText(_translate("Dialog", "Limpar"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "Nome"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "Preço"))
import icone_servico


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_cadastrar_servicos()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
