# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrar_produto.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastrar_produtos(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(745, 527)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 745, 522))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cadastrar_produtos = QtWidgets.QWidget()
        self.tab_cadastrar_produtos.setObjectName("tab_cadastrar_produtos")
        self.btn_limpar_produtos = QtWidgets.QPushButton(self.tab_cadastrar_produtos)
        self.btn_limpar_produtos.setGeometry(QtCore.QRect(242, 344, 100, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_limpar_produtos.setFont(font)
        self.btn_limpar_produtos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_limpar_produtos.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_limpar_produtos.setObjectName("btn_limpar_produtos")
        self.Preco_Produto = QtWidgets.QLineEdit(self.tab_cadastrar_produtos)
        self.Preco_Produto.setGeometry(QtCore.QRect(222, 200, 111, 20))
        self.Preco_Produto.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.Preco_Produto.setObjectName("Preco_Produto")
        self.btn_cadastro_produtos = QtWidgets.QPushButton(self.tab_cadastrar_produtos)
        self.btn_cadastro_produtos.setGeometry(QtCore.QRect(242, 252, 100, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cadastro_produtos.setFont(font)
        self.btn_cadastro_produtos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastro_produtos.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_cadastro_produtos.setObjectName("btn_cadastro_produtos")
        self.label_17 = QtWidgets.QLabel(self.tab_cadastrar_produtos)
        self.label_17.setGeometry(QtCore.QRect(402, 240, 121, 141))
        self.label_17.setStyleSheet("image: url(:/Produtos/Img/Produtos.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.Fundo = QtWidgets.QLabel(self.tab_cadastrar_produtos)
        self.Fundo.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.Fundo.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.Fundo.setText("")
        self.Fundo.setObjectName("Fundo")
        self.label_2 = QtWidgets.QLabel(self.tab_cadastrar_produtos)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 741, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.tab_cadastrar_produtos)
        self.label_6.setGeometry(QtCore.QRect(222, 180, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(self.tab_cadastrar_produtos)
        self.label_12.setGeometry(QtCore.QRect(222, 133, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.Observcao = QtWidgets.QLineEdit(self.tab_cadastrar_produtos)
        self.Observcao.setGeometry(QtCore.QRect(340, 200, 191, 20))
        self.Observcao.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.Observcao.setObjectName("Observcao")
        self.label_4 = QtWidgets.QLabel(self.tab_cadastrar_produtos)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 9, 500))
        self.label_4.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.Nome_Produto = QtWidgets.QLineEdit(self.tab_cadastrar_produtos)
        self.Nome_Produto.setGeometry(QtCore.QRect(222, 155, 309, 20))
        self.Nome_Produto.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.Nome_Produto.setObjectName("Nome_Produto")
        self.label_8 = QtWidgets.QLabel(self.tab_cadastrar_produtos)
        self.label_8.setGeometry(QtCore.QRect(342, 179, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.tab_cadastrar_produtos)
        self.label_5.setGeometry(QtCore.QRect(2, 481, 737, 9))
        self.label_5.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.tab_cadastrar_produtos)
        self.label_9.setGeometry(QtCore.QRect(730, 0, 9, 500))
        self.label_9.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.btn_cancelar_produtos = QtWidgets.QPushButton(self.tab_cadastrar_produtos)
        self.btn_cancelar_produtos.setGeometry(QtCore.QRect(242, 299, 100, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cancelar_produtos.setFont(font)
        self.btn_cancelar_produtos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelar_produtos.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_cancelar_produtos.setObjectName("btn_cancelar_produtos")
        self.Fundo.raise_()
        self.btn_limpar_produtos.raise_()
        self.Preco_Produto.raise_()
        self.btn_cadastro_produtos.raise_()
        self.label_17.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.label_12.raise_()
        self.Observcao.raise_()
        self.label_4.raise_()
        self.Nome_Produto.raise_()
        self.label_8.raise_()
        self.label_5.raise_()
        self.label_9.raise_()
        self.btn_cancelar_produtos.raise_()
        self.tabWidget.addTab(self.tab_cadastrar_produtos, "")
        self.tab_lista_de_produtos = QtWidgets.QWidget()
        self.tab_lista_de_produtos.setObjectName("tab_lista_de_produtos")
        self.label_3 = QtWidgets.QLabel(self.tab_lista_de_produtos)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 741, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_lista_de_produtos)
        self.tableWidget.setGeometry(QtCore.QRect(9, 40, 722, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.setColumnHidden(0,True)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label_43 = QtWidgets.QLabel(self.tab_lista_de_produtos)
        self.label_43.setGeometry(QtCore.QRect(730, 0, 9, 500))
        self.label_43.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        
        self.tableWidget.setColumnWidth(1, 150)
        self.tableWidget.setColumnWidth(2, 80)
        self.tableWidget.setColumnWidth(3, 150)


        self.label_43.setObjectName("label_43")
        self.label_42 = QtWidgets.QLabel(self.tab_lista_de_produtos)
        self.label_42.setGeometry(QtCore.QRect(0, 0, 9, 500))
        self.label_42.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_42.setObjectName("label_42")
        self.refresh = QtWidgets.QLabel(self.tab_lista_de_produtos)
        self.refresh.setGeometry(QtCore.QRect(698, 4, 41, 31))
        self.refresh.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"image: url(:/Produtos/Img/botao-atualizar.png);")
        self.refresh.setText("")
        self.refresh.setObjectName("refresh")
        self.frame = QtWidgets.QFrame(self.tab_lista_de_produtos)
        self.frame.setGeometry(QtCore.QRect(10, 390, 721, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_excluir_produtos = QtWidgets.QPushButton(self.frame)
        self.btn_excluir_produtos.setGeometry(QtCore.QRect(10, 50, 702, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_excluir_produtos.setFont(font)
        self.btn_excluir_produtos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir_produtos.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_excluir_produtos.setObjectName("btn_excluir_produtos")
        self.btn_pesquisar_produtos = QtWidgets.QPushButton(self.frame)
        self.btn_pesquisar_produtos.setGeometry(QtCore.QRect(366, 10, 345, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_pesquisar_produtos.setFont(font)
        self.btn_pesquisar_produtos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pesquisar_produtos.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_pesquisar_produtos.setObjectName("btn_pesquisar_produtos")
        self.label_46 = QtWidgets.QLabel(self.frame)
        self.label_46.setGeometry(QtCore.QRect(2, 100, 738, 9))
        self.label_46.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_46.setObjectName("label_46")
        self.line_pesquisar_produtos = QtWidgets.QLineEdit(self.frame)
        self.line_pesquisar_produtos.setGeometry(QtCore.QRect(10, 10, 345, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_pesquisar_produtos.setFont(font)
        self.line_pesquisar_produtos.setAutoFillBackground(False)
        self.line_pesquisar_produtos.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.line_pesquisar_produtos.setAlignment(QtCore.Qt.AlignCenter)
        self.line_pesquisar_produtos.setDragEnabled(False)
        self.line_pesquisar_produtos.setReadOnly(False)
        self.line_pesquisar_produtos.setClearButtonEnabled(False)
        self.line_pesquisar_produtos.setObjectName("line_pesquisar_produtos")
        self.tabWidget.addTab(self.tab_lista_de_produtos, "")
        self.label_44 = QtWidgets.QLabel(Dialog)
        self.label_44.setGeometry(QtCore.QRect(2, 509, 738, 9))
        self.label_44.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_44.setObjectName("label_44")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.Nome_Produto)
        Dialog.setTabOrder(self.Nome_Produto, self.Preco_Produto)
        Dialog.setTabOrder(self.Preco_Produto, self.Observcao)
        Dialog.setTabOrder(self.Observcao, self.btn_cadastro_produtos)
        Dialog.setTabOrder(self.btn_cadastro_produtos, self.btn_cancelar_produtos)
        Dialog.setTabOrder(self.btn_cancelar_produtos, self.btn_limpar_produtos)
        Dialog.setTabOrder(self.btn_limpar_produtos, self.tableWidget)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Cadastrar Produtos", "Cadastrar Produtos"))
        self.btn_limpar_produtos.setText(_translate("Dialog", "Limpar"))
        self.btn_cadastro_produtos.setText(_translate("Dialog", "Cadastrar"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Cadastrar Produtos no Sistema</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Preço</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Nome</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Observação</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btn_cancelar_produtos.setText(_translate("Dialog", "Cancelar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cadastrar_produtos), _translate("Dialog", "Cadastrar Produtos"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_cadastrar_produtos), _translate("Dialog", "Cadastrar Produtos no Sistema"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Lista de Produtos</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Preço"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Observação"))
        self.label_43.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_42.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btn_excluir_produtos.setText(_translate("Dialog", "Excluir"))
        self.btn_pesquisar_produtos.setText(_translate("Dialog", "Pesquisar"))
        self.label_46.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.line_pesquisar_produtos.setPlaceholderText(_translate("Dialog", "Digite o que deseja pesquisar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lista_de_produtos), _translate("Dialog", "Lista de Produtos"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_lista_de_produtos), _translate("Dialog", "Lista de Produtos Cadastrado no Sistema"))
        self.label_44.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
from icones import icone_produtos


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_cadastrar_produtos()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
