# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrar_servicos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastrar_servicos(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(745, 527)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 745, 522))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cadastrar_servicos = QtWidgets.QWidget()
        self.tab_cadastrar_servicos.setObjectName("tab_cadastrar_servicos")
        self.label_6 = QtWidgets.QLabel(self.tab_cadastrar_servicos)
        self.label_6.setGeometry(QtCore.QRect(212, 169, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_Cadastro_Servico = QtWidgets.QPushButton(self.tab_cadastrar_servicos)
        self.btn_Cadastro_Servico.setGeometry(QtCore.QRect(232, 242, 100, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Cadastro_Servico.setFont(font)
        self.btn_Cadastro_Servico.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Cadastro_Servico.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Cadastro_Servico.setObjectName("btn_Cadastro_Servico")
        self.label_4 = QtWidgets.QLabel(self.tab_cadastrar_servicos)
        self.label_4.setGeometry(QtCore.QRect(0, -4, 8, 430))
        self.label_4.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab_cadastrar_servicos)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 9, 500))
        self.label_3.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.tab_cadastrar_servicos)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 741, 40))
        self.label_2.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.tab_cadastrar_servicos)
        self.label_9.setGeometry(QtCore.QRect(730, 0, 9, 500))
        self.label_9.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.tab_cadastrar_servicos)
        self.label_8.setGeometry(QtCore.QRect(332, 169, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.tab_cadastrar_servicos)
        self.label.setGeometry(QtCore.QRect(392, 234, 121, 121))
        self.label.setStyleSheet("border-image: url(:/Servico/Img/Cadastro_Servico.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn_Limpar_Usuario = QtWidgets.QPushButton(self.tab_cadastrar_servicos)
        self.btn_Limpar_Usuario.setGeometry(QtCore.QRect(232, 334, 100, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Limpar_Usuario.setFont(font)
        self.btn_Limpar_Usuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Limpar_Usuario.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Limpar_Usuario.setObjectName("btn_Limpar_Usuario")
        self.Preco_Servico = QtWidgets.QLineEdit(self.tab_cadastrar_servicos)
        self.Preco_Servico.setGeometry(QtCore.QRect(212, 190, 111, 20))
        self.Preco_Servico.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.Preco_Servico.setObjectName("Preco_Servico")
        self.Nome_Servico = QtWidgets.QLineEdit(self.tab_cadastrar_servicos)
        self.Nome_Servico.setGeometry(QtCore.QRect(211, 140, 310, 20))
        self.Nome_Servico.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.Nome_Servico.setObjectName("Nome_Servico")
        self.label_12 = QtWidgets.QLabel(self.tab_cadastrar_servicos)
        self.label_12.setGeometry(QtCore.QRect(212, 120, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.Fundo = QtWidgets.QLabel(self.tab_cadastrar_servicos)
        self.Fundo.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.Fundo.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.Fundo.setText("")
        self.Fundo.setObjectName("Fundo")
        self.btn_Cancelar_Servico = QtWidgets.QPushButton(self.tab_cadastrar_servicos)
        self.btn_Cancelar_Servico.setGeometry(QtCore.QRect(232, 289, 100, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Cancelar_Servico.setFont(font)
        self.btn_Cancelar_Servico.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Cancelar_Servico.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Cancelar_Servico.setObjectName("btn_Cancelar_Servico")
        self.label_5 = QtWidgets.QLabel(self.tab_cadastrar_servicos)
        self.label_5.setGeometry(QtCore.QRect(0, 462, 738, 9))
        self.label_5.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.OBS_Servico = QtWidgets.QLineEdit(self.tab_cadastrar_servicos)
        self.OBS_Servico.setGeometry(QtCore.QRect(330, 190, 191, 20))
        self.OBS_Servico.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.OBS_Servico.setObjectName("OBS_Servico")
        self.Fundo.raise_()
        self.label_6.raise_()
        self.btn_Cadastro_Servico.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.label.raise_()
        self.btn_Limpar_Usuario.raise_()
        self.Preco_Servico.raise_()
        self.Nome_Servico.raise_()
        self.label_12.raise_()
        self.btn_Cancelar_Servico.raise_()
        self.label_5.raise_()
        self.OBS_Servico.raise_()
        self.tabWidget.addTab(self.tab_cadastrar_servicos, "")
        self.tab_lista_de_servicos = QtWidgets.QWidget()
        self.tab_lista_de_servicos.setObjectName("tab_lista_de_servicos")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_lista_de_servicos)
        self.tableWidget.setGeometry(QtCore.QRect(9, 40, 722, 351))
        self.tableWidget.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.setColumnHidden(0,True)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label_7 = QtWidgets.QLabel(self.tab_lista_de_servicos)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 741, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_7.setObjectName("label_7")
        self.frame_botoes_servicos = QtWidgets.QFrame(self.tab_lista_de_servicos)
        self.frame_botoes_servicos.setGeometry(QtCore.QRect(10, 391, 721, 101))
        self.frame_botoes_servicos.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.frame_botoes_servicos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botoes_servicos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botoes_servicos.setObjectName("frame_botoes_servicos")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_botoes_servicos)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_pesquisar_fornecedores = QtWidgets.QPushButton(self.frame_botoes_servicos)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_pesquisar_fornecedores.setFont(font)
        self.btn_pesquisar_fornecedores.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pesquisar_fornecedores.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_pesquisar_fornecedores.setObjectName("btn_pesquisar_fornecedores")
        self.verticalLayout.addWidget(self.btn_pesquisar_fornecedores)
        self.btn_alterar_servicos = QtWidgets.QPushButton(self.frame_botoes_servicos)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_alterar_servicos.setFont(font)
        self.btn_alterar_servicos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_alterar_servicos.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_alterar_servicos.setObjectName("btn_alterar_servicos")
        self.verticalLayout.addWidget(self.btn_alterar_servicos)
        self.btn_excluir_servicos = QtWidgets.QPushButton(self.frame_botoes_servicos)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_excluir_servicos.setFont(font)
        self.btn_excluir_servicos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir_servicos.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_excluir_servicos.setObjectName("btn_excluir_servicos")
        self.verticalLayout.addWidget(self.btn_excluir_servicos)
        self.label_43 = QtWidgets.QLabel(self.tab_lista_de_servicos)
        self.label_43.setGeometry(QtCore.QRect(730, 0, 9, 500))
        self.label_43.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_lista_de_servicos)
        self.label_44.setGeometry(QtCore.QRect(0, 0, 9, 500))
        self.label_44.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_lista_de_servicos)
        self.label_45.setGeometry(QtCore.QRect(0, 480, 738, 9))
        self.label_45.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_45.setObjectName("label_45")
        self.label_10 = QtWidgets.QLabel(self.tab_lista_de_servicos)
        self.label_10.setGeometry(QtCore.QRect(698, 4, 41, 31))
        self.label_10.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"image: url(:/Servico/Img/botao-atualizar.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_lista_de_servicos, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.Nome_Servico)
        Dialog.setTabOrder(self.Nome_Servico, self.Preco_Servico)
        Dialog.setTabOrder(self.Preco_Servico, self.OBS_Servico)
        Dialog.setTabOrder(self.OBS_Servico, self.btn_Cadastro_Servico)
        Dialog.setTabOrder(self.btn_Cadastro_Servico, self.btn_Cancelar_Servico)
        Dialog.setTabOrder(self.btn_Cancelar_Servico, self.btn_Limpar_Usuario)
        Dialog.setTabOrder(self.btn_Limpar_Usuario, self.tableWidget)
        Dialog.setTabOrder(self.tableWidget, self.btn_pesquisar_fornecedores)
        Dialog.setTabOrder(self.btn_pesquisar_fornecedores, self.btn_alterar_servicos)
        Dialog.setTabOrder(self.btn_alterar_servicos, self.btn_excluir_servicos)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Preço</span></p></body></html>"))
        self.btn_Cadastro_Servico.setText(_translate("Dialog", "Cadastrar"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Cadastrar Serviços no Sistema</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Observação</span></p></body></html>"))
        self.btn_Limpar_Usuario.setText(_translate("Dialog", "Limpar"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Nome</span></p></body></html>"))
        self.btn_Cancelar_Servico.setText(_translate("Dialog", "Cancelar"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cadastrar_servicos), _translate("Dialog", "Cadastrar Serviços"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_cadastrar_servicos), _translate("Dialog", "Cadastrar Serviços no Sistema"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Preços"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Observação"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Lista de Serviços</span></p></body></html>"))
        self.btn_pesquisar_fornecedores.setText(_translate("Dialog", "Pesquisar"))
        self.btn_alterar_servicos.setText(_translate("Dialog", "Alterar"))
        self.btn_excluir_servicos.setText(_translate("Dialog", "Excluir"))
        self.label_43.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_44.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_45.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lista_de_servicos), _translate("Dialog", "Lista de Serviços"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_lista_de_servicos), _translate("Dialog", "Lista de Serviços no Sistema"))
from icones import icone_servicos


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_cadastrar_servicos()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
