# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastro_Colaboradores.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastrar_colaboradores(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(745, 499)
        Dialog.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(9, 9, 727, 481))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cadastro_colaborador = QtWidgets.QWidget()
        self.tab_cadastro_colaborador.setObjectName("tab_cadastro_colaborador")
        self.label_17 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_17.setGeometry(QtCore.QRect(472, 242, 121, 116))
        self.label_17.setStyleSheet("border-image: url(:/Colaboradores/Img/cadastro.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.nome_usuario = QtWidgets.QLineEdit(self.tab_cadastro_colaborador)
        self.nome_usuario.setGeometry(QtCore.QRect(140, 107, 421, 20))
        self.nome_usuario.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.nome_usuario.setObjectName("nome_usuario")
        self.setor_usuario = QtWidgets.QLineEdit(self.tab_cadastro_colaborador)
        self.setor_usuario.setGeometry(QtCore.QRect(429, 152, 132, 20))
        self.setor_usuario.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.setor_usuario.setObjectName("setor_usuario")
        self.label_4 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 9, 448))
        self.label_4.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.btn_cancelar_usuario = QtWidgets.QPushButton(self.tab_cadastro_colaborador)
        self.btn_cancelar_usuario.setGeometry(QtCore.QRect(312, 287, 100, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cancelar_usuario.setFont(font)
        self.btn_cancelar_usuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelar_usuario.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_cancelar_usuario.setObjectName("btn_cancelar_usuario")
        self.label_8 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_8.setGeometry(QtCore.QRect(431, 129, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.nascimento_usuario = QtWidgets.QDateEdit(self.tab_cadastro_colaborador)
        self.nascimento_usuario.setGeometry(QtCore.QRect(302, 152, 122, 20))
        self.nascimento_usuario.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.nascimento_usuario.setObjectName("nascimento_usuario")
        self.label_13 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_13.setGeometry(QtCore.QRect(140, 219, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.btn_cadastro_usuario = QtWidgets.QPushButton(self.tab_cadastro_colaborador)
        self.btn_cadastro_usuario.setGeometry(QtCore.QRect(312, 240, 100, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cadastro_usuario.setFont(font)
        self.btn_cadastro_usuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastro_usuario.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_cadastro_usuario.setObjectName("btn_cadastro_usuario")
        self.cep_usuario = QtWidgets.QLineEdit(self.tab_cadastro_colaborador)
        self.cep_usuario.setGeometry(QtCore.QRect(140, 197, 111, 20))
        self.cep_usuario.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.cep_usuario.setObjectName("cep_usuario")
        self.btn_limpar_usuario = QtWidgets.QPushButton(self.tab_cadastro_colaborador)
        self.btn_limpar_usuario.setGeometry(QtCore.QRect(312, 332, 100, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_limpar_usuario.setFont(font)
        self.btn_limpar_usuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_limpar_usuario.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_limpar_usuario.setObjectName("btn_limpar_usuario")
        self.senha_usuario = QtWidgets.QLineEdit(self.tab_cadastro_colaborador)
        self.senha_usuario.setGeometry(QtCore.QRect(140, 287, 151, 20))
        self.senha_usuario.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.senha_usuario.setObjectName("senha_usuario")
        self.label_6 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_6.setGeometry(QtCore.QRect(140, 132, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_14 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_14.setGeometry(QtCore.QRect(304, 131, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_11 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_11.setGeometry(QtCore.QRect(140, 176, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_16.setGeometry(QtCore.QRect(140, 308, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_2 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 718, 40))
        self.label_2.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_5.setGeometry(QtCore.QRect(0, 440, 718, 9))
        self.label_5.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_12.setGeometry(QtCore.QRect(140, 84, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.confrimar_senha_usuario = QtWidgets.QLineEdit(self.tab_cadastro_colaborador)
        self.confrimar_senha_usuario.setGeometry(QtCore.QRect(140, 332, 151, 20))
        self.confrimar_senha_usuario.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.confrimar_senha_usuario.setObjectName("confrimar_senha_usuario")
        self.label_15 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_15.setGeometry(QtCore.QRect(140, 263, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.fundo = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.fundo.setGeometry(QtCore.QRect(0, 0, 725, 900))
        self.fundo.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.fundo.setText("")
        self.fundo.setObjectName("fundo")
        self.endereo_usuario = QtWidgets.QLineEdit(self.tab_cadastro_colaborador)
        self.endereo_usuario.setGeometry(QtCore.QRect(259, 197, 301, 20))
        self.endereo_usuario.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.endereo_usuario.setObjectName("endereo_usuario")
        self.login_usuario = QtWidgets.QLineEdit(self.tab_cadastro_colaborador)
        self.login_usuario.setGeometry(QtCore.QRect(140, 242, 151, 20))
        self.login_usuario.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.login_usuario.setObjectName("login_usuario")
        self.label_10 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_10.setGeometry(QtCore.QRect(260, 176, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.cpf_usuario = QtWidgets.QLineEdit(self.tab_cadastro_colaborador)
        self.cpf_usuario.setGeometry(QtCore.QRect(140, 152, 157, 20))
        self.cpf_usuario.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.cpf_usuario.setObjectName("cpf_usuario")
        self.label_9 = QtWidgets.QLabel(self.tab_cadastro_colaborador)
        self.label_9.setGeometry(QtCore.QRect(712, 0, 9, 448))
        self.label_9.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.fundo.raise_()
        self.label_17.raise_()
        self.nome_usuario.raise_()
        self.setor_usuario.raise_()
        self.label_4.raise_()
        self.btn_cancelar_usuario.raise_()
        self.label_8.raise_()
        self.nascimento_usuario.raise_()
        self.label_13.raise_()
        self.btn_cadastro_usuario.raise_()
        self.cep_usuario.raise_()
        self.btn_limpar_usuario.raise_()
        self.senha_usuario.raise_()
        self.label_6.raise_()
        self.label_14.raise_()
        self.label_11.raise_()
        self.label_16.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.label_12.raise_()
        self.confrimar_senha_usuario.raise_()
        self.label_15.raise_()
        self.endereo_usuario.raise_()
        self.login_usuario.raise_()
        self.label_10.raise_()
        self.cpf_usuario.raise_()
        self.label_9.raise_()
        self.tabWidget.addTab(self.tab_cadastro_colaborador, "")
        self.tab_cadastro_colaboradores = QtWidgets.QWidget()
        self.tab_cadastro_colaboradores.setObjectName("tab_cadastro_colaboradores")
        self.label_3 = QtWidgets.QLabel(self.tab_cadastro_colaboradores)
        self.label_3.setGeometry(QtCore.QRect(9, 9, 703, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_cadastro_colaboradores)
        self.tableWidget.setGeometry(QtCore.QRect(9, 40, 703, 332))
        self.tableWidget.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.frame_botoes_produtos = QtWidgets.QFrame(self.tab_cadastro_colaboradores)
        self.frame_botoes_produtos.setGeometry(QtCore.QRect(9, 378, 703, 62))
        self.frame_botoes_produtos.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.frame_botoes_produtos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botoes_produtos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botoes_produtos.setObjectName("frame_botoes_produtos")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_botoes_produtos)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_alterar_usuarios = QtWidgets.QPushButton(self.frame_botoes_produtos)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_alterar_usuarios.setFont(font)
        self.btn_alterar_usuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_alterar_usuarios.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_alterar_usuarios.setObjectName("btn_alterar_usuarios")
        self.verticalLayout.addWidget(self.btn_alterar_usuarios)
        self.btn_excluir_usuarios = QtWidgets.QPushButton(self.frame_botoes_produtos)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_excluir_usuarios.setFont(font)
        self.btn_excluir_usuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir_usuarios.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_excluir_usuarios.setObjectName("btn_excluir_usuarios")
        self.verticalLayout.addWidget(self.btn_excluir_usuarios)
        self.tabWidget.addTab(self.tab_cadastro_colaboradores, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btn_cancelar_usuario.setText(_translate("Dialog", "Cancelar"))
        self.label_8.setText(_translate("Dialog", "Setor"))
        self.label_13.setText(_translate("Dialog", "Login"))
        self.btn_cadastro_usuario.setText(_translate("Dialog", "Cadastrar"))
        self.btn_limpar_usuario.setText(_translate("Dialog", "Limpar"))
        self.label_6.setText(_translate("Dialog", "CPF"))
        self.label_14.setText(_translate("Dialog", "Nascimento"))
        self.label_11.setText(_translate("Dialog", "CEP"))
        self.label_16.setText(_translate("Dialog", "Confirmar Senha"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Cadastrar Colaboradores no Sistema</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "Nome"))
        self.label_15.setText(_translate("Dialog", "Senha"))
        self.label_10.setText(_translate("Dialog", "Endereço"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cadastro_colaborador), _translate("Dialog", "Cadastrar Colaboradores"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_cadastro_colaborador), _translate("Dialog", "Cadastrar Colaboradores no Sistema"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Lista de Clientes</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "CPF"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Nascimento"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Setor"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "CEP"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Endereço"))
        self.btn_alterar_usuarios.setText(_translate("Dialog", "Alterar"))
        self.btn_excluir_usuarios.setText(_translate("Dialog", "Excluir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cadastro_colaboradores), _translate("Dialog", "Lista de Colaboradores"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_cadastro_colaboradores), _translate("Dialog", "Listas de Colaboradores no Sistema"))
from icones import icone_colaboradores


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_cadastrar_colaboradores()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
