# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrar_fornecedores.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastrar_fornecedores(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(745, 527)
        Dialog.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 745, 522))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cadastrar_fornecedores = QtWidgets.QWidget()
        self.tab_cadastrar_fornecedores.setObjectName("tab_cadastrar_fornecedores")
        self.Fundo = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.Fundo.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.Fundo.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.Fundo.setText("")
        self.Fundo.setObjectName("Fundo")
        self.label_9 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_9.setGeometry(QtCore.QRect(730, 0, 9, 500))
        self.label_9.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 741, 40))
        self.label_2.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_5.setGeometry(QtCore.QRect(2, 481, 738, 9))
        self.label_5.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_3.setGeometry(QtCore.QRect(0, -4, 8, 430))
        self.label_3.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 9, 500))
        self.label_4.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.label_18 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_18.setGeometry(QtCore.QRect(160, 137, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_7 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_7.setGeometry(QtCore.QRect(160, 91, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.nome_fantasia = QtWidgets.QLineEdit(self.tab_cadastrar_fornecedores)
        self.nome_fantasia.setGeometry(QtCore.QRect(160, 112, 418, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nome_fantasia.setFont(font)
        self.nome_fantasia.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.nome_fantasia.setObjectName("nome_fantasia")
        self.email_fornecedores = QtWidgets.QLineEdit(self.tab_cadastrar_fornecedores)
        self.email_fornecedores.setGeometry(QtCore.QRect(318, 247, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.email_fornecedores.setFont(font)
        self.email_fornecedores.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.email_fornecedores.setObjectName("email_fornecedores")
        self.label_15 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_15.setGeometry(QtCore.QRect(368, 137, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_14.setGeometry(QtCore.QRect(160, 226, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.btn_cadastrar_fornecedor = QtWidgets.QPushButton(self.tab_cadastrar_fornecedores)
        self.btn_cadastrar_fornecedor.setGeometry(QtCore.QRect(463, 377, 115, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cadastrar_fornecedor.setFont(font)
        self.btn_cadastrar_fornecedor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastrar_fornecedor.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_cadastrar_fornecedor.setObjectName("btn_cadastrar_fornecedor")
        self.cpf_cnpj_fornecedores = QtWidgets.QLineEdit(self.tab_cadastrar_fornecedores)
        self.cpf_cnpj_fornecedores.setGeometry(QtCore.QRect(160, 157, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cpf_cnpj_fornecedores.setFont(font)
        self.cpf_cnpj_fornecedores.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.cpf_cnpj_fornecedores.setObjectName("cpf_cnpj_fornecedores")
        self.endereco_fornecedores = QtWidgets.QLineEdit(self.tab_cadastrar_fornecedores)
        self.endereco_fornecedores.setGeometry(QtCore.QRect(160, 202, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.endereco_fornecedores.setFont(font)
        self.endereco_fornecedores.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.endereco_fornecedores.setObjectName("endereco_fornecedores")
        self.label_11 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_11.setGeometry(QtCore.QRect(160, 182, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_16.setGeometry(QtCore.QRect(420, 182, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_13 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_13.setGeometry(QtCore.QRect(318, 226, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.razao_social = QtWidgets.QLineEdit(self.tab_cadastrar_fornecedores)
        self.razao_social.setGeometry(QtCore.QRect(368, 157, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.razao_social.setFont(font)
        self.razao_social.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.razao_social.setObjectName("razao_social")
        self.btn_cadastro_fornecedores = QtWidgets.QPushButton(self.tab_cadastrar_fornecedores)
        self.btn_cadastro_fornecedores.setGeometry(QtCore.QRect(160, 377, 115, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cadastro_fornecedores.setFont(font)
        self.btn_cadastro_fornecedores.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastro_fornecedores.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_cadastro_fornecedores.setObjectName("btn_cadastro_fornecedores")
        self.btn_cancelar_fornecedores = QtWidgets.QPushButton(self.tab_cadastrar_fornecedores)
        self.btn_cancelar_fornecedores.setGeometry(QtCore.QRect(315, 377, 115, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cancelar_fornecedores.setFont(font)
        self.btn_cancelar_fornecedores.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelar_fornecedores.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_cancelar_fornecedores.setObjectName("btn_cancelar_fornecedores")
        self.comboBox = QtWidgets.QComboBox(self.tab_cadastrar_fornecedores)
        self.comboBox.setGeometry(QtCore.QRect(470, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.telefone_fornecedores = QtWidgets.QLineEdit(self.tab_cadastrar_fornecedores)
        self.telefone_fornecedores.setGeometry(QtCore.QRect(160, 247, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.telefone_fornecedores.setFont(font)
        self.telefone_fornecedores.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.telefone_fornecedores.setObjectName("telefone_fornecedores")
        self.inscricao_estadual = QtWidgets.QLineEdit(self.tab_cadastrar_fornecedores)
        self.inscricao_estadual.setGeometry(QtCore.QRect(418, 202, 162, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.inscricao_estadual.setFont(font)
        self.inscricao_estadual.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.inscricao_estadual.setObjectName("inscricao_estadual")
        self.label_17 = QtWidgets.QLabel(self.tab_cadastrar_fornecedores)
        self.label_17.setGeometry(QtCore.QRect(160, 272, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.tipo_de_fornecedores = QtWidgets.QLineEdit(self.tab_cadastrar_fornecedores)
        self.tipo_de_fornecedores.setGeometry(QtCore.QRect(160, 297, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tipo_de_fornecedores.setFont(font)
        self.tipo_de_fornecedores.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.tipo_de_fornecedores.setObjectName("tipo_de_fornecedores")
        self.tabWidget.addTab(self.tab_cadastrar_fornecedores, "")
        self.tab_lista_fornecedores = QtWidgets.QWidget()
        self.tab_lista_fornecedores.setObjectName("tab_lista_fornecedores")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_lista_fornecedores)
        self.tableWidget.setGeometry(QtCore.QRect(9, 40, 722, 351))
        self.tableWidget.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.setColumnHidden(0,True)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.frame_botoes_fornecedores = QtWidgets.QFrame(self.tab_lista_fornecedores)
        self.frame_botoes_fornecedores.setGeometry(QtCore.QRect(10, 390, 721, 101))
        self.frame_botoes_fornecedores.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.frame_botoes_fornecedores.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botoes_fornecedores.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botoes_fornecedores.setObjectName("frame_botoes_fornecedores")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_botoes_fornecedores)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_pesquisar_fornecedores = QtWidgets.QPushButton(self.frame_botoes_fornecedores)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_pesquisar_fornecedores.setFont(font)
        self.btn_pesquisar_fornecedores.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pesquisar_fornecedores.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_pesquisar_fornecedores.setObjectName("btn_pesquisar_fornecedores")
        self.verticalLayout.addWidget(self.btn_pesquisar_fornecedores)
        self.btn_editar_fornecedores = QtWidgets.QPushButton(self.frame_botoes_fornecedores)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_editar_fornecedores.setFont(font)
        self.btn_editar_fornecedores.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_editar_fornecedores.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_editar_fornecedores.setObjectName("btn_editar_fornecedores")
        self.verticalLayout.addWidget(self.btn_editar_fornecedores)
        self.btn_excluir_fornecedor = QtWidgets.QPushButton(self.frame_botoes_fornecedores)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_excluir_fornecedor.setFont(font)
        self.btn_excluir_fornecedor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir_fornecedor.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_excluir_fornecedor.setObjectName("btn_excluir_fornecedor")
        self.verticalLayout.addWidget(self.btn_excluir_fornecedor)
        self.label_10 = QtWidgets.QLabel(self.tab_lista_fornecedores)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 741, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_10.setObjectName("label_10")
        self.label_43 = QtWidgets.QLabel(self.tab_lista_fornecedores)
        self.label_43.setGeometry(QtCore.QRect(730, 0, 9, 500))
        self.label_43.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_lista_fornecedores)
        self.label_44.setGeometry(QtCore.QRect(0, 0, 9, 500))
        self.label_44.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_44.setObjectName("label_44")
        self.refresh = QtWidgets.QLabel(self.tab_lista_fornecedores)
        self.refresh.setGeometry(QtCore.QRect(698, 4, 41, 31))
        self.refresh.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"image: url(:/Item/Img/botao-atualizar.png);")
        self.refresh.setText("")
        self.refresh.setObjectName("refresh")
        self.tabWidget.addTab(self.tab_lista_fornecedores, "")
        self.label_45 = QtWidgets.QLabel(Dialog)
        self.label_45.setGeometry(QtCore.QRect(0, 509, 738, 9))
        self.label_45.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_45.setObjectName("label_45")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.nome_fantasia)
        Dialog.setTabOrder(self.nome_fantasia, self.cpf_cnpj_fornecedores)
        Dialog.setTabOrder(self.cpf_cnpj_fornecedores, self.razao_social)
        Dialog.setTabOrder(self.razao_social, self.endereco_fornecedores)
        Dialog.setTabOrder(self.endereco_fornecedores, self.inscricao_estadual)
        Dialog.setTabOrder(self.inscricao_estadual, self.telefone_fornecedores)
        Dialog.setTabOrder(self.telefone_fornecedores, self.email_fornecedores)
        Dialog.setTabOrder(self.email_fornecedores, self.tipo_de_fornecedores)
        Dialog.setTabOrder(self.tipo_de_fornecedores, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.btn_cadastro_fornecedores)
        Dialog.setTabOrder(self.btn_cadastro_fornecedores, self.btn_cancelar_fornecedores)
        Dialog.setTabOrder(self.btn_cancelar_fornecedores, self.btn_cadastrar_fornecedor)
        Dialog.setTabOrder(self.btn_cadastrar_fornecedor, self.tableWidget)
        Dialog.setTabOrder(self.tableWidget, self.btn_pesquisar_fornecedores)
        Dialog.setTabOrder(self.btn_pesquisar_fornecedores, self.btn_excluir_fornecedor)
        Dialog.setTabOrder(self.btn_excluir_fornecedor, self.btn_editar_fornecedores)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Cadastrar Fornecedor</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">CPF / CNPJ</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p>Nome Fantasia</p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Razão social</span></p><p><br/></p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Nº Telefone</span></p></body></html>"))
        self.btn_cadastrar_fornecedor.setText(_translate("Dialog", "Limpar"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Endereço</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Inscrição estadual</span></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">E-mail</span></p></body></html>"))
        self.btn_cadastro_fornecedores.setText(_translate("Dialog", "Cadastrar"))
        self.btn_cancelar_fornecedores.setText(_translate("Dialog", "Cancelar"))
        self.comboBox.setItemText(0, _translate("Dialog", "** Categoria **"))
        self.comboBox.setItemText(1, _translate("Dialog", "Pessoa Juridica"))
        self.comboBox.setItemText(2, _translate("Dialog", "Pessoa Física"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Tipo de Fornecedor</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cadastrar_fornecedores), _translate("Dialog", "Cadastrar Fornecedores"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_cadastrar_fornecedores), _translate("Dialog", "Cadastrar Fornecedores no Sistema"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome Fantasia"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "CPF / CNPJ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Razão Social"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Endereço"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Inscrição Estadual"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "N° Telefone"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "E-Mail"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Tipo de Fornecedor"))
        self.btn_pesquisar_fornecedores.setText(_translate("Dialog", "Pesquisar"))
        self.btn_editar_fornecedores.setText(_translate("Dialog", "Editar"))
        self.btn_excluir_fornecedor.setText(_translate("Dialog", "Excluir"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Lista de Fornecedores</span></p></body></html>"))
        self.label_43.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_44.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lista_fornecedores), _translate("Dialog", "Lista de Fornecedores"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_lista_fornecedores), _translate("Dialog", "Lista de Itens Fornecedores no Sistema"))
        self.label_45.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
from icones import icone_fornecedores


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_cadastrar_fornecedores()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
