# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrar_clientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastrar_clientes(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(745, 526)
        Dialog.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 745, 527))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cadastrar_clientes = QtWidgets.QWidget()
        self.tab_cadastrar_clientes.setObjectName("tab_cadastrar_clientes")
        self.label_27 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_27.setGeometry(QtCore.QRect(442, 289, 121, 116))
        self.label_27.setStyleSheet("image: url(:/icone_clientes/Img/Cliente.png);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.btn_cadastro_cliente = QtWidgets.QPushButton(self.tab_cadastrar_clientes)
        self.btn_cadastro_cliente.setGeometry(QtCore.QRect(292, 288, 115, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cadastro_cliente.setFont(font)
        self.btn_cadastro_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastro_cliente.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_cadastro_cliente.setObjectName("btn_cadastro_cliente")
        self.telefone_cliente = QtWidgets.QLineEdit(self.tab_cadastrar_clientes)
        self.telefone_cliente.setGeometry(QtCore.QRect(150, 248, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.telefone_cliente.setFont(font)
        self.telefone_cliente.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.telefone_cliente.setObjectName("telefone_cliente")
        self.label_28 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_28.setGeometry(QtCore.QRect(150, 227, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_29.setGeometry(QtCore.QRect(308, 227, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.email_cliente = QtWidgets.QLineEdit(self.tab_cadastrar_clientes)
        self.email_cliente.setGeometry(QtCore.QRect(308, 248, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.email_cliente.setFont(font)
        self.email_cliente.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.email_cliente.setObjectName("email_cliente")
        self.nascimento = QtWidgets.QDateEdit(self.tab_cadastrar_clientes)
        self.nascimento.setGeometry(QtCore.QRect(448, 203, 122, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nascimento.setFont(font)
        self.nascimento.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.nascimento.setObjectName("nascimento")
        self.label_30 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_30.setGeometry(QtCore.QRect(358, 138, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_cadastrar_clientes)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_2.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_31 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_31.setGeometry(QtCore.QRect(150, 92, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_32.setGeometry(QtCore.QRect(448, 183, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_33.setGeometry(QtCore.QRect(150, 138, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.cpf_cliente = QtWidgets.QLineEdit(self.tab_cadastrar_clientes)
        self.cpf_cliente.setGeometry(QtCore.QRect(150, 158, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cpf_cliente.setFont(font)
        self.cpf_cliente.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.cpf_cliente.setObjectName("cpf_cliente")
        self.btn_cancelar_cliente = QtWidgets.QPushButton(self.tab_cadastrar_clientes)
        self.btn_cancelar_cliente.setGeometry(QtCore.QRect(292, 335, 115, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cancelar_cliente.setFont(font)
        self.btn_cancelar_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelar_cliente.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_cancelar_cliente.setObjectName("btn_cancelar_cliente")
        self.nome_cliente = QtWidgets.QLineEdit(self.tab_cadastrar_clientes)
        self.nome_cliente.setGeometry(QtCore.QRect(150, 113, 418, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nome_cliente.setFont(font)
        self.nome_cliente.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.nome_cliente.setObjectName("nome_cliente")
        self.apelido_ciente = QtWidgets.QLineEdit(self.tab_cadastrar_clientes)
        self.apelido_ciente.setGeometry(QtCore.QRect(358, 158, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.apelido_ciente.setFont(font)
        self.apelido_ciente.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.apelido_ciente.setObjectName("apelido_ciente")
        self.endereco_cliente = QtWidgets.QLineEdit(self.tab_cadastrar_clientes)
        self.endereco_cliente.setGeometry(QtCore.QRect(150, 203, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.endereco_cliente.setFont(font)
        self.endereco_cliente.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.endereco_cliente.setObjectName("endereco_cliente")
        self.btn_cadastrar_cliente = QtWidgets.QPushButton(self.tab_cadastrar_clientes)
        self.btn_cadastrar_cliente.setGeometry(QtCore.QRect(292, 380, 115, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cadastrar_cliente.setFont(font)
        self.btn_cadastrar_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastrar_cliente.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_cadastrar_cliente.setObjectName("btn_cadastrar_cliente")
        self.label_34 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_34.setGeometry(QtCore.QRect(150, 183, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_35.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.label_35.setAutoFillBackground(False)
        self.label_35.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_36.setGeometry(QtCore.QRect(0, 0, 741, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_37.setGeometry(QtCore.QRect(0, 0, 9, 500))
        self.label_37.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_38.setGeometry(QtCore.QRect(730, 0, 9, 500))
        self.label_38.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_cadastrar_clientes)
        self.label_39.setGeometry(QtCore.QRect(2, 487, 738, 9))
        self.label_39.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_39.setObjectName("label_39")
        self.label_35.raise_()
        self.label_27.raise_()
        self.btn_cadastro_cliente.raise_()
        self.telefone_cliente.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.email_cliente.raise_()
        self.nascimento.raise_()
        self.label_30.raise_()
        self.comboBox_2.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.cpf_cliente.raise_()
        self.btn_cancelar_cliente.raise_()
        self.nome_cliente.raise_()
        self.apelido_ciente.raise_()
        self.endereco_cliente.raise_()
        self.btn_cadastrar_cliente.raise_()
        self.label_34.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.tabWidget.addTab(self.tab_cadastrar_clientes, "")
        self.tab_lista_de_clientes = QtWidgets.QWidget()
        self.tab_lista_de_clientes.setObjectName("tab_lista_de_clientes")
        self.label_40 = QtWidgets.QLabel(self.tab_lista_de_clientes)
        self.label_40.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.label_40.setAutoFillBackground(False)
        self.label_40.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_lista_de_clientes)
        self.tableWidget_3.setGeometry(QtCore.QRect(9, 40, 722, 351))
        self.tableWidget_3.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(8)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tableWidget_3.setColumnHidden(0,True)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        self.label_41 = QtWidgets.QLabel(self.tab_lista_de_clientes)
        self.label_41.setGeometry(QtCore.QRect(0, 0, 741, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_lista_de_clientes)
        self.label_42.setGeometry(QtCore.QRect(0, 0, 9, 500))
        self.label_42.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab_lista_de_clientes)
        self.label_43.setGeometry(QtCore.QRect(730, 0, 9, 500))
        self.label_43.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_lista_de_clientes)
        self.label_44.setGeometry(QtCore.QRect(2, 486, 738, 9))
        self.label_44.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_44.setObjectName("label_44")
        self.frame = QtWidgets.QFrame(self.tab_lista_de_clientes)
        self.frame.setGeometry(QtCore.QRect(10, 390, 721, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_excluir_clientes = QtWidgets.QPushButton(self.frame)
        self.btn_excluir_clientes.setGeometry(QtCore.QRect(10, 70, 702, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_excluir_clientes.setFont(font)
        self.btn_excluir_clientes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir_clientes.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_excluir_clientes.setObjectName("btn_excluir_clientes")
        self.btn_editar_clientes = QtWidgets.QPushButton(self.frame)
        self.btn_editar_clientes.setGeometry(QtCore.QRect(10, 40, 702, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_editar_clientes.setFont(font)
        self.btn_editar_clientes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_editar_clientes.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_editar_clientes.setObjectName("btn_editar_clientes")
        self.btn_pesquisar_Clientes = QtWidgets.QPushButton(self.frame)
        self.btn_pesquisar_Clientes.setGeometry(QtCore.QRect(10, 10, 702, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_pesquisar_Clientes.setFont(font)
        self.btn_pesquisar_Clientes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pesquisar_Clientes.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_pesquisar_Clientes.setObjectName("btn_pesquisar_Clientes")
        self.label_45 = QtWidgets.QLabel(self.frame)
        self.label_45.setGeometry(QtCore.QRect(2, 100, 738, 9))
        self.label_45.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_45.setObjectName("label_45")
        self.refresh = QtWidgets.QLabel(self.tab_lista_de_clientes)
        self.refresh.setGeometry(QtCore.QRect(698, 4, 41, 31))
        self.refresh.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"image: url(:/icone_clientes/Img/botao-atualizar.png);")
        self.refresh.setText("")
        self.refresh.setObjectName("refresh")
        self.label_40.raise_()
        self.tableWidget_3.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.frame.raise_()
        self.label_44.raise_()
        self.refresh.raise_()
        self.tabWidget.addTab(self.tab_lista_de_clientes, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.nome_cliente)
        Dialog.setTabOrder(self.nome_cliente, self.cpf_cliente)
        Dialog.setTabOrder(self.cpf_cliente, self.apelido_ciente)
        Dialog.setTabOrder(self.apelido_ciente, self.endereco_cliente)
        Dialog.setTabOrder(self.endereco_cliente, self.nascimento)
        Dialog.setTabOrder(self.nascimento, self.telefone_cliente)
        Dialog.setTabOrder(self.telefone_cliente, self.email_cliente)
        Dialog.setTabOrder(self.email_cliente, self.comboBox_2)
        Dialog.setTabOrder(self.comboBox_2, self.btn_cadastro_cliente)
        Dialog.setTabOrder(self.btn_cadastro_cliente, self.btn_cancelar_cliente)
        Dialog.setTabOrder(self.btn_cancelar_cliente, self.btn_cadastrar_cliente)
        Dialog.setTabOrder(self.btn_cadastrar_cliente, self.tableWidget_3)
        Dialog.setTabOrder(self.tableWidget_3, self.btn_pesquisar_Clientes)
        Dialog.setTabOrder(self.btn_pesquisar_Clientes, self.btn_editar_clientes)
        Dialog.setTabOrder(self.btn_editar_clientes, self.btn_excluir_clientes)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_cadastro_cliente.setText(_translate("Dialog", "Cadastrar"))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Nº Telefone</span></p></body></html>"))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">E-mail</span></p></body></html>"))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Apelido</span></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "** Categoria **"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Pessoa Juridica"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Pessoa Física"))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Nome</span></p></body></html>"))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Nascimento</span></p></body></html>"))
        self.label_33.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">CPF / CNPJ</span></p></body></html>"))
        self.btn_cancelar_cliente.setText(_translate("Dialog", "Cancelar"))
        self.btn_cadastrar_cliente.setText(_translate("Dialog", "Limpar"))
        self.label_34.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Endereço</span></p></body></html>"))
        self.label_36.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Cadastrar Clientes no Sistema</span></p></body></html>"))
        self.label_37.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_38.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_39.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cadastrar_clientes), _translate("Dialog", "Cadastrar Clientes"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_cadastrar_clientes), _translate("Dialog", "Cadastrar Clientes no Sistema"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "CPF / CNPJ"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Apelido"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Endereço"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Nascimento"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "N° Telefone"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "E-mail"))
        self.label_41.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Lista de Clientes</span></p></body></html>"))
        self.label_42.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_43.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_44.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btn_excluir_clientes.setText(_translate("Dialog", "Excluir"))
        self.btn_editar_clientes.setText(_translate("Dialog", "Editar"))
        self.btn_pesquisar_Clientes.setText(_translate("Dialog", "Pesquisar"))
        self.label_45.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lista_de_clientes), _translate("Dialog", "Lista de Clientes"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_lista_de_clientes), _translate("Dialog", "Lista de Clientes Cadastrado no Sistema"))
from icones import icone_clientes


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_cadastrar_clientes()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
