# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastro_Colaboradores.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastrar_Colaboradores(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(571, 430)
        self.Fundo = QtWidgets.QLabel(Dialog)
        self.Fundo.setGeometry(QtCore.QRect(0, 0, 571, 430))
        self.Fundo.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.Fundo.setText("")
        self.Fundo.setObjectName("Fundo")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 571, 30))
        self.label_2.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 8, 430))
        self.label_3.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 8, 430))
        self.label_4.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 424, 571, 8))
        self.label_5.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(68, 178, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Login_Usuario = QtWidgets.QLineEdit(Dialog)
        self.Login_Usuario.setGeometry(QtCore.QRect(68, 240, 151, 20))
        self.Login_Usuario.setObjectName("Login_Usuario")
        self.Nascimento_Usuario = QtWidgets.QDateEdit(Dialog)
        self.Nascimento_Usuario.setGeometry(QtCore.QRect(230, 150, 122, 20))
        self.Nascimento_Usuario.setObjectName("Nascimento_Usuario")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(68, 134, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.CPF_Usuario = QtWidgets.QLineEdit(Dialog)
        self.CPF_Usuario.setGeometry(QtCore.QRect(68, 150, 157, 20))
        self.CPF_Usuario.setObjectName("CPF_Usuario")
        self.ID_Usuario = QtWidgets.QLineEdit(Dialog)
        self.ID_Usuario.setGeometry(QtCore.QRect(68, 105, 73, 20))
        self.ID_Usuario.setObjectName("ID_Usuario")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(68, 90, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Senha_Usuario = QtWidgets.QLineEdit(Dialog)
        self.Senha_Usuario.setGeometry(QtCore.QRect(68, 285, 151, 20))
        self.Senha_Usuario.setObjectName("Senha_Usuario")
        self.CEP_Usuario = QtWidgets.QLineEdit(Dialog)
        self.CEP_Usuario.setGeometry(QtCore.QRect(68, 195, 111, 20))
        self.CEP_Usuario.setObjectName("CEP_Usuario")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(68, 222, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(359, 134, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.Setor_Usuario = QtWidgets.QLineEdit(Dialog)
        self.Setor_Usuario.setGeometry(QtCore.QRect(357, 150, 132, 20))
        self.Setor_Usuario.setObjectName("Setor_Usuario")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(188, 178, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(565, 0, 8, 430))
        self.label_9.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.Nome_Usuario = QtWidgets.QLineEdit(Dialog)
        self.Nome_Usuario.setGeometry(QtCore.QRect(148, 105, 341, 20))
        self.Nome_Usuario.setObjectName("Nome_Usuario")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(150, 90, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.Endereo_Usuario = QtWidgets.QLineEdit(Dialog)
        self.Endereo_Usuario.setGeometry(QtCore.QRect(187, 195, 301, 20))
        self.Endereo_Usuario.setObjectName("Endereo_Usuario")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(232, 134, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(68, 266, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.Confrimar_Senha_Usuario = QtWidgets.QLineEdit(Dialog)
        self.Confrimar_Senha_Usuario.setGeometry(QtCore.QRect(68, 330, 151, 20))
        self.Confrimar_Senha_Usuario.setObjectName("Confrimar_Senha_Usuario")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(68, 310, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(400, 240, 121, 116))
        self.label_17.setStyleSheet("border-image: url(:/Colaboradores/Img/cadastro.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.btn_Cancelar_Usuario = QtWidgets.QPushButton(Dialog)
        self.btn_Cancelar_Usuario.setGeometry(QtCore.QRect(240, 285, 100, 23))
        self.btn_Cancelar_Usuario.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Cancelar_Usuario.setObjectName("btn_Cancelar_Usuario")
        self.btn_Limpar_Usuario = QtWidgets.QPushButton(Dialog)
        self.btn_Limpar_Usuario.setGeometry(QtCore.QRect(240, 330, 100, 23))
        self.btn_Limpar_Usuario.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Limpar_Usuario.setObjectName("btn_Limpar_Usuario")
        self.btn_Cadastro_Usuario = QtWidgets.QPushButton(Dialog)
        self.btn_Cadastro_Usuario.setGeometry(QtCore.QRect(240, 238, 100, 23))
        self.btn_Cadastro_Usuario.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(216, 216, 216);\n"
"    color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.btn_Cadastro_Usuario.setObjectName("btn_Cadastro_Usuario")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Cadastrar Colaboradores no Sistema</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "CEP"))
        self.label_6.setText(_translate("Dialog", "CPF"))
        self.label_7.setText(_translate("Dialog", "ID"))
        self.label_13.setText(_translate("Dialog", "Login"))
        self.label_8.setText(_translate("Dialog", "Setor"))
        self.label_10.setText(_translate("Dialog", "Endereço"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "Nome"))
        self.label_14.setText(_translate("Dialog", "Nascimento"))
        self.label_15.setText(_translate("Dialog", "Senha"))
        self.label_16.setText(_translate("Dialog", "Confirmar Senha"))
        self.btn_Cancelar_Usuario.setText(_translate("Dialog", "Cancelar"))
        self.btn_Limpar_Usuario.setText(_translate("Dialog", "Limpar"))
        self.btn_Cadastro_Usuario.setText(_translate("Dialog", "Cadastrar"))
from Icones import Icone_Colaboradores


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Cadastrar_Colaboradores()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
